### ISSUE TITLE
Doesn't support profiles

### ISSUE THREAD

**Issue by martintreurnicht** [lonelyplanet/aws-mfa#13]
When using the `--profile` switch, it doesn't work as expected. I know that makes it a hell of a lot more complicated because of how the profiles work on the aws cli tool, but this might be an issue for a couple of people, especially the ones that are concerned enough about security to use MFA in the first place

**Comment by sciurus** [comment]
That's a good point. `aws-mfa` could check when it is wrapping a command with a `--profile` argument and change behavior accordingly. We'd need to pass the argument through when calling `aws`, and we'd need to add profile-specific locations for reading and writing the MFA devices and session tokens.
