### ISSUE TITLE
No way to clear credentials?

### ISSUE THREAD

**Issue by SeanBlader** [lonelyplanet/aws-mfa#18]
Unfortunately my time was off on my computer by one hour for some reason, and now it looks like I'll have to wait for 12 hours to clear the invalid credentials before I can use the command line again?

**Comment by leejones** [comment]
The MFA credentials are stored at `~/.aws/mfa_credentials`. You can delete that file and run `aws-mfa` again fetch new credentials.

**Comment by leejones** [comment]
I'm going to close this issue for now. Please let us know if my previous suggestion doesn't solve the issue for you.
